#baseurl = "https://devcows.github.io/hugo-universal-theme/" # Configure URL. if using gh-pages https://github.com/<username>/hugo-universal-theme URL: https://<username>.github.io/hugo-universal-theme/
baseurl = "https://zonge-international.github.io/ZongeWebDev/" 
#baseurl = "http://localhost:1313/ZongeWebDev/" 
relativeURLs = true
canonifyURLs = true
title = "Zonge"
theme = "hugo-universal-theme"
#themesDir = "./."
languageCode = "en-us"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"
# Enable comments by entering your Disqus shortname
# disqusShortname = "devcows"
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

#Allow download using html
[markup.goldmark.renderer]
unsafe = true

# number of words of summarized post content (default 70)
summaryLength = 70

# Define the number of posts per page
paginate = 10

# not pluralize title pages by default
pluralizelisttitles = false

[menu]


# Main menu
#[[menu.main]]
#    name       = "Home"
#    identifier = "menu.home"
#    url        = "/"
#    weight     = 1

##############################
# Methods ####################
##############################


[[menu.main]]
    name       = "Methods"
    identifier = "menu.methods"
    url        = "/img/mt-model-e13664090974923_m.png"
    weight     = 2

[[menu.main]]
    name       = "Ground Methods"
    identifier = "section.ground"
    url        = ""
    weight     = 1
    parent     = "menu.methods"
    post       = 1

[[menu.main]]
    name       = "Airborne Methods"
    identifier = "section.airborne"
    url        = ""
    weight     = 2
    parent     = "menu.methods"
    post       = 2

[[menu.main]]
    name       = "Induced Polarization"
    url        = "/Methods/GroundMethods/ip/"
    weight     = 1
    parent     = "section.ground"

[[menu.main]]
    name       = "Controlled Source AMT"
    url        = "/Methods/GroundMethods/csamt/"
    weight     = 2
    parent     = "section.ground"

[[menu.main]]
    name       = "Magnetotellurics"
    url        = "/Methods/GroundMethods/mt/"
    weight     = 3
    parent     = "section.ground"

[[menu.main]]
    name       = "TEM"
    url        = "/Methods/GroundMethods/tem/"
    weight     = 4
    parent     = "section.ground"

[[menu.main]]
    name       = "Gravity"
    url        = "/Methods/GroundMethods/gravity/"
    weight     = 4
    parent     = "section.ground"

[[menu.main]]
    name       = "Drone Magnetics"
    url        = "/Methods/AirboneMethods/airbone_magnetics/"
    weight     = 1
    parent     = "section.airborne"


##############################
# Targets ####################
##############################

[[menu.main]]
    name       = "Targets"
    identifier = "menu.targets"
    url        = "/img/Alaska-reinterp-3D.png"
    weight     = 3

[[menu.main]]
    name       = "Targets"
    identifier = "section.targets"
    url        = ""
    weight     = 1
    parent     = "menu.targets"
    post       = 1

[[menu.main]]
    name       = "Mining"
    identifier = "section.mining"
    url        = "/Targets/mining/"
    parent     = "section.targets"
    weight     = 1

[[menu.main]]
    name       = "Geothermal"
    identifier = "section.geothermal"
    url        = "/Targets/geothermal/"
    parent     = "section.targets"
    weight     = 2

[[menu.main]]
    name       = "Groundwater"
    identifier = "section.groundwater"
    url        = "/Targets/groundwater/"
    parent     = "section.targets"
    weight     = 3


##############################
# Instruments ################
##############################


[[menu.main]]
    name       = "Instruments"
    identifier = "menu.instruments"
    url        = "/img/img_7813_m.jpg"
    weight     = 4

[[menu.main]]
    name       = "Generators"
    identifier = "section.generators"
    url        = ""
    weight     = 4
    parent     = "menu.instruments"
    post       = 1
	
[[menu.main]]
    name       = "Transmitters"
    identifier = "section.transmitters"
    url        = ""
    weight     = 2
    parent     = "menu.instruments"
	post       = 2

[[menu.main]]
    name       = "Receivers"
    identifier = "section.receivers"
    url        = ""
    weight     = 1
    parent     = "menu.instruments"	
	post       = 1

[[menu.main]]
    name       = "Sensors"
    identifier = "section.sensors"
    url        = ""
    weight     = 3
    parent     = "menu.instruments"
	post       = 2

[[menu.main]]
    name       = "Accessories"
    identifier = "section.accessories"
    url        = "/accessories/"
    weight     = 5
    parent     = "menu.instruments"
    post       = 2
	
[[menu.main]]
    name       = "ZMG-9"
    url        = "/instruments/Generators/zmg9/"
    weight     = 1
    parent     = "section.generators"	

[[menu.main]]
    name       = "ZMG-30"
    url        = "/instruments/Generators/zmg30/"
    weight     = 2
    parent     = "section.generators"	

[[menu.main]]
    name       = "GGT-10"
	url        = "/instruments/TX/ggt10/"
    weight     = 1
    parent     = "section.transmitters"

[[menu.main]]
    name       = "GGT-30"
	url        = "/instruments/TX/ggt30/"
    weight     = 2
    parent     = "section.transmitters"
	
[[menu.main]]
    name       = "ZT-30B"
	url        = "/instruments/TX/ZT30B/"
    weight     = 3
    parent     = "section.transmitters"
		
[[menu.main]]
    name       = "XMT-G"
    url        = "/instruments/TX/XMTG/"
    weight     = 4
    parent     = "section.transmitters"

[[menu.main]]
    name       = "GDP3224"
    identifier = "section.gdp"
    url        = "/instruments/RX/GDP3224/"
    weight     = 1
    parent     = "section.receivers"	
	post       = 1
	
[[menu.main]]
    name       = "ZEN"
    identifier = "section.zen"
    url        = "/instruments/RX/ZEN/"
    weight     = 2
    parent     = "section.receivers"	
	post       = 2


[[menu.main]]
    name       = "ANT-4"
    identifier = "section.ant4"
    url        = "/instruments/Sensors/ant4/"
    weight     = 1
    parent     = "section.sensors"	
	post       = 1
	
[[menu.main]]
    name       = "ANT-6"
    identifier = "section.ant6"
    url        = "/instruments/Sensors/ant6/"
    weight     = 2
    parent     = "section.sensors"	
	post       = 2	

[[menu.main]]
    name       = "ANT-7"
    identifier = "section.ant7"
    url        = "/instruments/Sensors/ant7/"
    weight     = 3
    parent     = "section.sensors"	
	post       = 3	

[[menu.main]]
    name       = "TEM-4"
    identifier = "section.tem4"
    url        = "/instruments/Sensors/tem4/"
    weight     = 4
    parent     = "section.sensors"	
	post       = 4	


[[menu.main]]
    name       = "Reels"
    identifier = "section.reels"
    url        = "/Instruments/Accessories/reels/"
    weight     = 1
    parent     = "section.accessories"	
	post       = 7	

[[menu.main]]
    name       = "Misc"
    identifier = "section.misc"
    url        = "/Instruments/Accessories/misc/"
    weight     = 2
    parent     = "section.accessories"	
	post       = 7	

##############################
# Software ################
##############################


[[menu.main]]
    name       = "Software"
    identifier = "menu.software"
    url        = "/img/gdp_mt6_m.jpg"
    weight     = 5

[[menu.main]]
    name       = "Processing"
    identifier = "section.processing"
    url        = ""
    weight     = 1
    parent     = "menu.software"
    post       = 1
	
[[menu.main]]
    name       = "Inversion"
    identifier = "section.inversion"
    url        = ""
    weight     = 2
    parent     = "menu.software"
	post       = 2

##############################
# About ######################
##############################
	
[[menu.main]]
    name       = "About Us"
    identifier = "menu.about"
    url        = "about/about/"
    weight     = 6

[[menu.main]]
    name       = "About Us"
    url        = "/about/about/"
    weight     = 1
    parent     = "menu.about"

[[menu.main]]
    name       = "Our Team"
    url        = "/about/teams/"
    weight     = 2
    parent     = "menu.about"

[[menu.main]]
    name       = "Safety"
    url        = "/about/safety/"
    weight     = 3
    parent     = "menu.about"

[[menu.main]]
    name       = "Contact Us"
    url        = "/contact/"
    weight     = 4
    parent     = "menu.about"




# Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "Phone"
    url = "tel:+1 (520)327-5501"
    pre = "<i class='fas fa-2x fa-phone'></i>"

[[menu.topbar]]
    weight = 5
    name = "Email"
    url = "mailto:zonge@zonge.com"
    pre = "<i class='fas fa-2x fa-envelope'></i>"

[params]
    viewMorePostLink = "/blog/"
    author = "Zonge"
    defaultKeywords = ["devcows", "hugo", "go"]
    mainSections = ["blog"]
    defaultDescription = "Zonge International"

    # Google Maps widget: If `googleMapsApiKey` is not set, no key will be passed to Google (which likely results in a broken map widget).
    enableGoogleMaps = true
    googleMapsApiKey = "AIzaSyAv7Sza8NSp9_l_g8G2vlo0H4ydEPn_2jY"

    latitude = "32.27012"
    longitude = "-110.91468"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "blue"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 50 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - register your account to https://formspree.io/register
    # - login and create new form
    # - set your form's endpoint url under 'formspree_action' below
    # - upload the generated site to your server
    # - test a dummy email yourself
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io endpoint url
    formspree_action = "https://formspree.io/sample/of/endpoint"
    contact_form_ajax = false

    # Formspree form supports Google reCAPTCHA Key (type v2).
    # If you use this feature, you should enable reCAPTCHA feature in the Formspree dashboard.
    #
    # By default, Formspree use a redirect page for recaptcha widget.
    # If you use a recaptcha widget in your contact page, you should do next steps.
    # (if you don't want, skip these steps)
    #
    #   1. register your site on Google recaptcha admin page: https://www.google.com/recaptcha/admin
    #   2. select reCAPTCHA v2 and checkbox widget type.
    #   3. remember site key and secret key.
    #   4. enter secret key into "Custom reCAPTCHA Key" field in your Formspree form setting page.
    #   5. change `enableRecaptchaInContactForm` is to true
    #   6. enter site key into `googleRecaptchaKey` to enable a recaptcha widget in your page.
    #
    enableRecaptchaInContactForm = true
    googleRecaptchaKey = "site_key_for_google_recaptcha"

    about_us = "<p>Zonge is a world leader in the application of electromagnetic methods to subsurface imaging challenges</p>"
    copyright = "© 2025 Zonge International. All rights reserved."

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    dropdown_mouse_over = false

    disabled_logo = false
    logo_text = "Zonge International"

    #logo = "img/zonge_logo_tag_289_200x100.png"
	logo = "img/logo.png"
	
    #logo_small = "img/logo-small.png"
    logo_small = "img/logo.png"

    contact_url = "/contact"
    address = """<p class="text-uppercase"><strong>Zonge International, Inc</strong>
        <br>
		<br>3475 N Dodge Blvd
        <br>Tucson, AZ 85716
        <br>		
		<br>9595 Prototype Ct
        <br>Reno, NV 89521
        <br>
   
		
      </p>
      """

[permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = false
    text = """<p class="hidden-sm hidden-xs">Contact us at +1 (520)327-5501 or zonge@zonge.com</p>
      <p class="hidden-md hidden-lg"><a href="tel:+420 777 555 333" data-animate-hover="pulse"><i class="fas fa-phone"></i></a>
      <a href="mailto:zonge@zonge.com" data-animate-hover="pulse"><i class="fas fa-envelope"></i></a>
      </p>
      """

# Enable and disable widgets for the right sidebar
#[params.widgets]
#    categories = true
#    tags = true
#    search = true

[params.carouselCustomers]
    items = 5
    auto_play = true
    slide_speed = 2000
    pagination_speed = 1000

[params.carouselTestimonials]
    items = 4
    auto_play = true
    slide_speed = 2000
    pagination_speed = 1000

[params.carouselHomepage]
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more information take a look at the README.
    enable = true
    auto_play = true
    slide_speed = 2000
    pagination_speed = 1000
    

[params.features]
    enable = true
    cols = 3 # Default: 3, Available values 2,3,4,6
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more information take a look at the README.

[params.testimonials]
    enable = false
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more information take a look at the README.
    title = "Conversations"
    subtitle = "News and conversations "

[params.see_more]
    enable = false
    icon = "far fa-file-alt"
    title = "Do you want to see more?"
    subtitle = "We have prepared for you more than 40 different HTML pages, including 5 variations of homepage."
    link_url = "#"
    link_text = "Check other homepages"

[params.clients]
    enable = false
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more information take a look at the README.
    title = "Our Clients"
    subtitle = ""

[params.recent_posts]
    enable = false
    title = "Conversations"
    subtitle = "What we are working on, where to find us next, and new ideas"
    hide_summary = false

[params.footer.recent_posts]
    enable = false

[taxonomies]
  category = "categories"
  tag = "tags"
  author = "authors"
